name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      # Step 4: Run Python code
      - name: Run Python Code
        run: |
          python your_python_file.py  # Replace with the actual filename of your Python script

      # Step 5: Run tests (if any)
      - name: Run tests
        run: |
          python -m unittest discover tests/  # If you have tests, this will run them
        continue-on-error: true  # The pipeline will continue even if tests fail

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the deploy step runs after the build step
    if: github.ref == 'refs/heads/main'  # Only deploy from the main branch

    steps:
      # Step 1: Checkout the code again for the deploy step
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy (add your deploy commands here)
      - name: Deploy Application
        run: |
          echo "Deploying application..."  # Replace this with your actual deployment commands

